# Generated by Django 4.2.3 on 2023-08-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp_car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pulsacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('pulsaciones_por_minuto', models.IntegerField()),
            ],
        ),
    ]
