# Generated by Django 4.2.3 on 2023-08-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp_car', '0003_medicion'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicionCompleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humedad', models.FloatField()),
                ('temperatura', models.FloatField()),
                ('pulsaciones', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
