# Generated by Django 5.0.2 on 2024-03-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp_car', '0006_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicioncompleto',
            name='humedad',
        ),
        migrations.AlterField(
            model_name='medicioncompleto',
            name='collar_id',
            field=models.CharField(max_length=5000),
        ),
    ]
